// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    community: [
        'intro',
        'mission',
        'roadmap',
        'development/process/index',
        {
            label: 'Developer meetings',
            type: 'category',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'meetings',
                },
            ],
            link: {
                type: 'doc',
                id: 'meetings',
            },
        },
        {
            label: 'Policies',
            type: 'category',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'policies',
                },
            ],
        },
        'research',
    ],
};

module.exports = sidebars;

